# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL='https://evugphtantcjndfdleaq.supabase.co'
SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dWdwaHRhbnRjam5kZmRsZWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTA0OTIsImV4cCI6MjA1NzM2NjQ5Mn0._rI2JeU4fjPp910rhB6obn5ryincfqh7z9RTUNd4OR4'

